# Generated by Django 5.0.6 on 2024-06-08 20:24

import django.db.models.deletion
from django.db import migrations, models

_exist_category = []


def get_or_create_qna_category():
    from pybo.models import Category

    if not _exist_category:
        default_category, _ = Category.objects.get_or_create(name='qna')
        _exist_category.append(default_category.id)

    return _exist_category[0]


class Migration(migrations.Migration):
    dependencies = [
        ('pybo', '0007_alter_answer_id_alter_comment_id_alter_question_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(default=get_or_create_qna_category, on_delete=django.db.models.deletion.PROTECT,
                                    to='pybo.category'),
            preserve_default=False,
        ),
    ]
