# Generated by Django 5.0.6 on 2024-06-08 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0008_category_question_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='view_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
