# Generated by Django 5.0.6 on 2024-06-09 11:26

from django.db import migrations, models


def set_default_path(apps, schema_editor):
    Category = apps.get_model('pybo', 'Category')
    for category in Category.objects.all():
        if category.name == 'qna':
            category.path = 'qna'
            category.name = '질문과답변'
        else:
            category.path = category.name
        category.save()


class Migration(migrations.Migration):
    dependencies = [
        ('pybo', '0009_question_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='path',
            field=models.CharField(max_length=50, null=True, default=None),
            preserve_default=False,
        ),
        migrations.RunPython(set_default_path),
        migrations.AlterField(
            model_name='category',
            name='path',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
